spring:
  application:
    name: calculate-vacation-salary

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_salary_db
    username: vacation_user
    password: vacation_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # или create для первого запуска
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always  # запускать init.sql
#      data-locations: classpath:data.sql

server:
  port: 8080

logging:
  level:
    com.hamming: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG